name: safepass_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  csv: ^5.0.2
  flutter:
    sdk: flutter
    
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  go_router: ^15.1.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.0.7  
  flutter_dotenv: ^5.2.1
  http: ^1.4.0  
  web: ^1.1.1
  http_parser: ^4.1.2
  cron: ^0.6.2

dev_dependencies:
  flutter_test:
      sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env.development
